### ISSUE TITLE
Question with `Unwrap`

### ISSUE THREAD

**Issue by Vaida12345** [bernndr/swift-macros#1]
Hey
Nice work on the macros. Just wondering by you have the `Unwrap` macro when you can use the syntax sugar `??`

```swift
let optionalValue: String? = nil
let unwrapValue = optionalValue ?? "swift"
```

**Comment by bernndr** [comment]
The unwrap macro has been designed to simplify writing code like this:

```swift
var optionalBool: Bool?
if !(optionalBool ?? true) {
  
}

if !#unwrap(optionalBool, default: true) {
  
}
```

I'm not sure if it's actually useful.
If you have suggestions, they are welcome.

**Comment by bernndr** [comment]
Now that I think about it, it doesn't make much sense... I will remove the macro in the future.
